services:
  frontend:
    build: .
    ports:
      - "${PORT:-80}:80"
    environment:
      - GATUS_URL=${GATUS_URL:-gatus:8080}
    depends_on:
      - gatus

  gatus:
    image: twinproduction/gatus:stable
    volumes:
      - ./config:/config:ro
